import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Header from '~/components/Header'
import Contents from '~/components/Contents'
import { Container } from '@mui/material'
import type { GetStaticPaths, GetStaticProps, NextPage } from 'next'
import { useShopItemsQuery } from '~/generated/graphql'
import { ShopItemType } from 'interface/shop'

const inter = Inter({ subsets: ['latin'] })
import { client } from '../lib/graphql'

export const getStaticProps: GetStaticProps = async ({ params }) => {
  if (!params) {
    return {
      props: { item: {} }
    }
  }
  const items = useShopItemsQuery
  return {
    props: {items},
    revalidate: 1, // このページに変更があった場合にビルドやるよ
    notFound: !items,
  }
}

interface Params {
  items: ShopItemType[]
}

const Home: NextPage<Params> = ({items}) =>  {
  return (
    <>
      <Head>
        <title>Huyou</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main style={{}}>
        <Container sx={{ textAlign: 'center' }}>
          <Contents shopItem={items}/>
        </Container>
      </main>
    </>
  )
}

export default Home